### ISSUE TITLE
[BUG] `Unable to expand resources because the source file` when using listkeys()

### ISSUE THREAD

**Issue by sebassem** [Azure/PSRule.Rules.Azure#2829] opened 2024-04-22 12:00 UTC
### Description of the issue

I have the following code using the keyVault AVM module and trying to reference a storage account key

`
secrets: {
      secureList: [
        {
          name: storageRef.name
          value: storageRef.listKeys().keys[0].value
          attributesExp: 1702648632
          attributesNbf: 10000
        }
      ]
    }
`
When PSRule runs I always get this error :

_Failed to expand bicep source '/home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/ptn/finops-toolkit/finops-hub/tests/e2e/defaults/main.test.bicep'. Exception calling "GetBicepResources" with "2" argument(s): "Unable to expand resources because the source file '/home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/ptn/finops-toolkit/finops-hub/tests/e2e/defaults/main.test.bicep' was not valid. An error occurred evaluating expression '[parameters('value')]' line 9939. The parameter named 'value' was not set or a defaultValue was defined."_

### Error messages

_Failed to expand bicep source '/home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/ptn/finops-toolkit/finops-hub/tests/e2e/defaults/main.test.bicep'. Exception calling "GetBicepResources" with "2" argument(s): "Unable to expand resources because the source file '/home/runner/work/bicep-registry-modules/bicep-registry-modules/avm/ptn/finops-toolkit/finops-hub/tests/e2e/defaults/main.test.bicep' was not valid. An error occurred evaluating expression '[parameters('value')]' line 9939. The parameter named 'value' was not set or a defaultValue was defined."_

### Reproduction

https://github.com/sebassem/bicep-registry-modules/actions/workflows/avm.ptn.finops-toolkit.finops-hub.yml

### Version of PSRule

2.9.0

**Comment by sebassem** [comment] 2024-04-24 14:05
Hey @BernieWhite, do we have a fix for this in an upcoming release? I'm asking as we are getting similar issues in AVM pattern modules..

**Comment by BernieWhite** [comment] 2024-04-24 14:28
Hi @sebassem, yes, initial investigation is done and I am working on a fix. There is a bit of complexity to this issue, but I hope to close this issue in the next day or so followed with a pre-release.

If you have another similar issue that you think is related to a similar pattern of `listKeys()` or other secret value please feel free to reference the actions run in this issue and I'll double check we have a fix for that as well.

If you feel that the issue is unrelated maybe add another issue so we can track it separately.

**Closed** 2024-04-25 09:54 UTC
Labels: bug, feature: pre-flight-expansion
