### ISSUE TITLE
[BUG] PSRule not handling optionality marker ? as expected

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/PSRule.Rules.Azure#2700] opened 2024-02-22 09:01 UTC
### Description of the issue

It looks to me that PSRule is not capable of handling the `optionality marker ?` properly. The marker is used whether if a property is required or not on a user-defined type most commonly, however it can also be used with a parameter, to specify if it is a required parameter or not.

```bicep
@description('Route table configuration.')
param parRouteTable typRouteTable?
```

### Error messages

```
2024-02-21T17:33:28.3000658Z ##[error]Failed to expand bicep source '/home/runner/work/platform/platform/./deployments/sub/mgmt-env-001/parameters/main.dev.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Unable to expand resources because the source file '/home/runner/work/platform/platform/./deployments/sub/mgmt-env-001/parameters/main.dev.bicepparam' was not valid. The type for parameter 'parRouteTable' was not defined or invalid."
```

### Reproduction

`main.dev.bicepparam`
```bicep
using '../main.bicep'

param parEnvironment = 'dev'
```

`main.bicep`
```bicep
@description('Route table configuration.')
param parRouteTable typRouteTable?

@description('This module will deploy the base infrastructure required for any subscriptions.')
module modPtnWrapper './src/deploy.bicep' = {
  name: 'modPtnWrapper-${parBaseTime}'
  params: {
    parRouteTable: parRouteTable
  }
}
```
`deploy.bicep (nested module in main.bicep)`
```bicep
@description('The custom routes to deploy.')
param parRouteTable typRouteTable?
```

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.33.2

### Additional context

I was unsure whether if the issue should he here or in the PSRule repository.

**Comment by BernieWhite** [comment] 2024-02-25 15:27
@BenjaminEngeset Are you able to provide `typRouteTable` can't repo this currently. Generally nullable parameters and types are supported and should work.

Are you using imports at all?

**Comment by BernieWhite** [comment] 2024-02-28 17:07
@BenjaminEngeset Support will ship with v1.34.0, which should ship next week. But feel free to checkout the next pre-release.

**Comment by BernieWhite** [comment] 2024-03-02 07:10
Closing as duplicate of #2537

**Closed by BernieWhite** 2024-03-02 07:10 UTC
Labels: bug, feature: pre-flight-expansion
