### ISSUE TITLE
[BUG] Bicep CLI Cannot be found, even though I added bicep.exe to Env Variable.

### ISSUE THREAD

**Issue by josesos** [Azure/PSRule.Rules.Azure#2873] opened 2024-05-20 02:01 UTC
### Description of the issue

I'm running PSRule.Azure locally. When I do, I get an error:  "Bicep CLI can not be found. Consider installing Bicep or setting the PSRULE_AZURE_BICEP_PATH environment variable to resolve this issue."

I have already added the bicep.exe directory to PSRULE_AZURE_BICEP_PATH but it did not work. I have tried adding bicep to the PATH, but that did not work either.

The interesting thing is that it was working 12 hours ago. I tried today, without making any changes to my setup or configuration and it just did not work.

### Error messages

   ERROR  Exception calling "GetBicepVersion" with "1" argument(s): "Bicep CLI can not be found. Consider installing Bicep or setting the PSRULE_AZURE_BICEP_PATH environment variable to resolve this issue."
   ERROR  Failed to expand bicep source 'C:\Users\josesos\source\repos\LearningLab\MLE.Lab\src\MLE.Web.API.AzureResources\Bicep\Parameters\StorageAccount.bicepparam'. Exception calling "GetBicepParamResources" with "2" argument(s): "Object reference not set to an instance of an object."

### Reproduction

I followed these instructions:

1. Created a ps-rule.yaml file.
2. Ran
Install-Module -Name 'PsRule' -Repository PSGallery -Scope CurrentUser -Force
Install-Module -Name 'PSRule.Rules.Azure' -Repository PSGallery -Scope CurrentUser -Force
3. Created my bicep files
4. Added Env Variable
[Environment]::SetEnvironmentVariable("PSRULE_AZURE_BICEP_PATH", "%USERPROFILE%\.Azure\bin\bicep.exe", "User")
5. Ran command
Assert-PSRule  -InputPath .

Got error

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.36.0 

### Additional context

Bicep CLI version: 0.27.1

**Comment by BernieWhite** [comment] 2024-05-20 13:12
Hi @josesos thanks for reporting the issue.

Can I please confirm/ check some additional information about your environment:

- Are you running PSRule locally?
- Please check the `PSRULE_AZURE_BICEP_PATH` environment variable by outputting the variable with `$Env:PSRULE_AZURE_BICEP_PATH` is as expected.
  - In my local testing a slash may be missing, causing the path to be invalid.
- After setting the environment variable locally the changes won't apply to the current process, so open a new session and retry.

If a similar exception is still generated, create a convention for debugging to do this:

- From the current working path where you are running `Assert-PSRule` create a new sub-directory named `.ps-rule`.
- In the sub-directory create a new file `Debug.Rule.ps1`, the final path `.ps-rule/Debug.Rule.ps1`.
- Add the following content to the file.

```powershell
Export-PSRuleConvention 'DebugBicepCLI' -Initialize {
    Write-Host "PSRULE_AZURE_BICEP_PATH=$($Env:PSRULE_AZURE_BICEP_PATH)"
    Write-Host "Bicep CLI PATH=$((Get-ChildItem -Path $Env:PSRULE_AZURE_BICEP_PATH | Select-Object -First 1).FullName)"
    Write-Host "Bicep CLI version=$(& $Env:PSRULE_AZURE_BICEP_PATH --version)"
}
```

Add `-Convention DebugBicepCLI` to your command line. For example:

```powershell
Assert-PSRule  -InputPath . -Convention DebugBicepCLI
```

The convention should dump the result of these variables for verification.

**Comment by josesos** [comment] 2024-05-20 15:26
Thank you!

Using the Debug Rules helped me solve the issue!

For reasons I don't understand setting the env variable to "%USERPROFILE%.Azure\bin\bicep.exe" was making Bicep CLI path be returned as "C:\Users\xxxxxxx\source\repos\LearningLab\MLE.Lab\src\MLE.Web.API.AzureResources\Bicep\%USERPROFILE%.Azure\bin\bicep.exe", which is not where the bicep exe is. It obviously doesn't exist. :)

I kept changing the env variable to explicitely use address with no USERPROFILE variable, and kept updating the variable and restarting PowerShell until it too. It is working now.

Thank you!

**Comment by BernieWhite** [comment] 2024-05-20 23:17
Hi @josesos. No worries. It sounds like the problem is solved and it was related to an environment specific issue.

As a result, I will proceed to close the issue. If that it not correct, please let me know.

**Closed by BernieWhite** 2024-05-20 23:17 UTC
Labels: bug, feature: pre-flight-expansion

**Comment by josesos** [comment] 2024-05-22 16:49
[like]  Jose Sosa reacted to your message:
________________________________
